core/urls.py
from django.urls import path,include
from .views import *
from rest_framework import routers
from .viewset import ItemViewSet
from .filters import *

router = routers.DefaultRouter()
router.register('item', ItemViewSet)

app_name = 'core'

urlpatterns = [
    path('api/',include(router.urls)),
    path('', HomeView.as_view(), name='home'),
    path('collection/', search, name='collection'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView, name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    #path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),

    path('cancel/', payment_cancel, name='cancel'),
    path('success/', payment_success, name='success'),
    path('create-checkout-session/', CreateCheckoutSessionView.as_view(), name='create-checkout-session')
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

hack/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- Mobile Web-app fullscreen -->

  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">

  <!-- Meta tags -->

  <meta name="description" content="Extended Bootstrap 4 Template">
  <meta name="author" content="Goran Hrustic">
  <link rel="icon" href="{% static 'assets/svg/favicon.ico' %}">

  <!-- Vendor stylesheets -->
  <script type="text/javascript">

		function getCookie(name) {
		    var cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        var cookies = document.cookie.split(';');
		        for (var i = 0; i < cookies.length; i++) {
		            var cookie = cookies[i].trim();
		            // Does this cookie string begin with the name we want?
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}


		function uuidv4() {
		  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
		    var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
		    return v.toString(16);
		  });
		}




		let device = getCookie('device')

		if (device == null || device == undefined){
			device = uuidv4()
		}

		document.cookie ='device=' + device + ";domain=;path=/"

	</script>
  <!-- Template stylesheets -->

  <!-- Title -->

  <title>{% block head_title %}{% endblock %}</title>

  {% block extra_head %}
  {% endblock %}
  <!-- Vendor stylesheets -->

  <link rel="stylesheet" media="all" href="{% static 'css/vendor/animate.css' %}" />
  <link rel="stylesheet" media="all" href="{% static 'css/vendor/font-awesome.css' %}" />
  <link rel="stylesheet" media="all" href="{% static 'css/vendor/linear-icons.css' %}" />
  <link rel="stylesheet" media="all" href="{% static 'css/vendor/owl.carousel.css' %}" />
  <link rel="stylesheet" media="all" href="{% static 'css/vendor/jquery.lavalamp.css' %}" />

  <!-- Template stylesheets -->

  <link rel="stylesheet" media="all" href="{% static 'css/style.css' %}" />
</head>

{% include "navbar.html" %}

</head>

<body>
  {% include "navbar.html" %}

  <div class="mt-5 pt-4">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endif %}
  </div>

  {% block content %}
  {% endblock content %}

  {% block extra_body %}
  {% endblock %}

  {% include "footer.html" %}
  <script src="{% static 'js/vendor/jquery.min.js' %}"></script>
  <script src="{% static 'js/vendor/bootstrap.bundle.js' %}"></script>
  <script src="{% static 'js/vendor/in-view.min.js' %}"></script>
  <script src="{% static 'js/vendor/jquery.lavalamp.js' %}"></script>
  <script src="{% static 'js/vendor/owl.carousel.js' %}"></script>
  <script src="{% static 'js/vendor/rellax.js' %}"></script>
  <script src="{% static 'js/vendor/wow.js' %}"></script>
  <script src="{% static 'js/vendor/tabzy.js' %}"></script>
  <script src="{% static 'js/vendor/isotope.pkgd.js' %}"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  <!-- Template Scripts -->

  <script src="{% static 'js/main.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>


  {% block extra_scripts %}
  {% endblock extra_scripts %}
</body>



</html>

templates/cancel.html
<html>
<head>
  <title>Checkout canceled</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
  </section>
</body>
</html>

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

  <main >
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Checkout form</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}
              
              {% if contact %}
              
              <h3>Contact detail</h3> 
              <div class="md-form mb-5">
                <input type='text' placeholder='' id='name' name='name' class='form-control' />
                <label for="name" class="">Name</label>
              </div>
              <div class="md-form mb-5">
                <input type='phone' placeholder='' id='phone' name='phone' class='form-control' />
                <label for="phone" class="">Contact No.</label>
              </div>
              <div class="md-form mb-5">
                <input type='email' placeholder='' id='email' name='email' class='form-control' />
                <label for="email" class="">Email Id</label>
              </div>
              {% endif %}
                
              <h3>Shipping address</h3>

              <div class='hideable_shipping_form'>

                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address' class='form-control' />
                  <label for="shipping_address" class="">Address</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control' />
                  <label for="shipping_address2" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
                </div>

              </div>

              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
                <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}

              <hr>
              <h3>Payment option</h3>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>

        </div>

        <div class="col-md-4 mb-4">
          {% include "order_snippet.html" %}
        </div>

      </div>

    </div>
  </main>

{% endblock content %}

{% block extra_scripts %}
<script>
var hideable_shipping_form = $('.hideable_shipping_form');

var use_default_shipping = document.querySelector("input[name=use_default_shipping]");

use_default_shipping.addEventListener('change', function() {
  if (this.checked) {
    hideable_shipping_form.hide();
  } else {
    hideable_shipping_form.show();
  }
})


</script>
{% endblock extra_scripts %}

templates/collection.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% block content %}
<section class="py-3">
  <div class="container">
    <div class="row">

      <!-- Product sidebar -->

      <div class="col-lg-3 sidebar sidebar-mobile" id="open-mobile-filters">
        <div class="sidebar-content">

          <!-- Header -->

          <div class="sidebar-header clearfix d-lg-none">
            <button type="button" class="close toggle-show p-3" data-show="open-mobile-filters" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>

          <!-- Search -->
          <form action="" method="get">

            <div class="bg-white p-2 p-lg-3 mb-2 mb-lg-4 shadow-sm br-sm">
              <div class="input-group">
                {% render_field filter.form.name class="form-control form-control-sm" placeholder="Search" aria-label="Search" aria-describedby="button-addon2" %}
                <div class="input-group-append">
                  <button class="btn btn-primary btn-sm" type="submit" id="button-addon2">Go!</button>
                </div>
              </div>
            </div>

            <!-- Slider range -->
            <div class="bg-white p-2 p-lg-3 mb-2 mb-lg-4 shadow-sm br-sm">

              <a class="pre-label px-0" data-toggle="collapse" href="#collapseExamplePrice" role="button"
                aria-expanded="false" aria-controls="collapseExamplePrice">
                <small>Slider</small>
              </a>

              <div class="collapse show" id="collapseExamplePrice">
                <div class="pt-3">
                  <div class="d-flex justify-content-between">
                    <span>Price</span>
                    <span>
                      Rs <b class="price-value">365</b>
                    </span>
                  </div>
                  {% render_field filter.form.price__lt type="range" class="custom-range price-range" id="customRange1" min="0" max="500" step="5" %}
                  <div class="d-flex justify-content-between">
                    <small>Rs 0</small>
                    <small>Rs 500</small>
                  </div>
                </div>
              </div>

            </div>

            <!-- Checkbox group -->
            <div class="form-group col-sm-8 col-md-6">

              <div>

                <label class="checkbox-inline">

                </label>

              </div>
            </div>
            <div class="bg-white p-2 p-lg-3 mb-2 mb-lg-4 shadow-sm br-sm">

              <a class="pre-label px-0" data-toggle="collapse" href="#collapseExampleCheckbox" role="button"
                aria-expanded="false" aria-controls="collapseExampleCheckbox">
                <small>Checkboxes</small>
              </a>

              <div class="collapse show" id="collapseExampleCheckbox">
                <ul class="list-group list-group-clean pt-4">
                  {% for choice in filter.form.category %}
                  <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{ choice.tag }}
                    <span class="custom-control custom-control-sm custom-control-light custom-checkbox">
                      {{ choice.choice_label }}
                    </span>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>


            <div class="bg-white p-2 p-lg-3 mb-2 mb-lg-4 shadow-sm br-sm">

              <a class="pre-label px-0" data-toggle="collapse" href="#collapseExampleSize" role="button"
                aria-expanded="false" aria-controls="collapseExampleSize">
                <small>Sizes</small>
              </a>

              <div class="collapse show" id="collapseExampleSize">
                <div class="d-flex justify-content-between pt-4">
                  {% for choice in filter.form.fit %}
                  <span class="btn-group-toggle" data-toggle="buttons">
                    <label class="btn btn-outline-primary active">
                      {{ choice.tag }} {{ choice.choice_label }}
                    </label>
                  </span>
                  {% endfor %}
                </div>
              </div>

            </div>
            <button type="submit" class="btn btn-primary">Apply Filtes</button>
            <hr>
          </form>
          <a href="/collection"><button class="btn btn-primary">Remove all Filtes</button></a>
        </div>
      </div>

      <!-- Products content -->

      <div class="col-lg-9">

        <!-- Products header -->

        <!-- <div class="bg-white p-2 p-lg-3 shadow-sm mb-2 mb-lg-4">
                    <div class="d-flex justify-content-between">                    
                        <!-- Right -->

        <!--  <div>
                            <div class="form-inline">
                                <div class="form-group mb-0">
                                    <label for="exampleFormControlSelect2" class="mr-3 d-none d-lg-block"><small>Sort by</small></label>
                                    <select class="form-control form-control-sm" id="exampleFormControlSelect2">
                                        <option>Name</option>
                                        <option>Price</option>
                                    </select>
                                </div>
                                <div class="d-lg-none ml-2">
                                    <button class="btn btn-primary btn-sm toggle-show" data-show="open-mobile-filters">
                                        <strong>
                                            <i class="icon icon-text-align-center"></i>
                                            <span class="d-none d-sm-inline-block">Filters</span>
                                        </strong>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> -->

        <!-- Products collection -->

        <div class="row gutters-mobile">
          {% for object in filter.qs %}
          <div class="col-6 col-xl-4">
            <div class="card card-fill border-0 mb-2 mb-lg-4 shadow-sm">
              <div class="card-image">
                <a href="{{object.get_absolute_url}}">
                  <img src="{{object.image.url}}" class="card-img-top" alt="...">
                </a>
              </div>
              <div class="card-body p-3 p-lg-4">
                <div class="d-flex justify-content-between align-items-center">
                  <div>
                    <h2 class="card-title mb-1 h5">
                      <a href="{{object.get_absolute_url}}">
                        {{object.name}}
                      </a>
                    </h2>
                    {% if object.discount_price %}
                    <small class="pre-label text-muted">
                      <span>Rs {{object.discount_price}}</span>
                      <s>Rs {{object.price}}</s>
                    </small>
                    {% else %}
                    <small class="pre-label text-muted">
                      <span>Rs {{object.price}}</span>
                    </small>
                    {% endif %}
                  </div>
                  <div>
                    <a href="{{object.get_add_to_cart_url}}" class="d-inline-block" data-toggle="tooltip"
                      data-placement="top" title="" data-original-title="Add to cart">
                      <i class="icon icon-cart font-size-xl"></i>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>

        <!-- Pagination -->

        <!-- <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center py-3 py-lg-4">
                        <li class="page-item disabled">
                            <a class="page-link page-link-first" href="#" tabindex="-1" aria-disabled="true">Prev</a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item active"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">4</a></li>
                        <li class="page-item">
                            <a class="page-link" href="#">Next</a>
                        </li>
                    </ul>
                </nav> -->

      </div>
    </div>
  </div>

</section>




{% endblock content %}

templates/footer.html
    <footer class="bg-white">
        <div class="container text-center">
            <div class="wow fadeIn" data-wow-delay=".4s">
                <p><i class="icon icon-layer display-4"></i></p>
                <ul class="list-group list-group-horizontal list-group-clean justify-content-center">
                    <li class="list-group-item pr-3"><a href="#">Our store</a></li>
                    <li class="list-group-item pr-3"><a href="#">Shop</a></li>
                    <li class="list-group-item pr-3"><a href="#">Categories</a></li>
                    <li class="list-group-item pr-3"><a href="#">Info</a></li>
                    <li class="list-group-item pr-3"><a href="#">Contact</a></li>
                </ul>
            </div>
            <div class="wow fadeIn" data-wow-delay=".8s">
                <p class="text-muted">
                    <small>All rights reserved 2020 © <a href="drdjango.ml">WebSigma</a></small>
                </p>
            </div>
        </div>
    </footer>

templates/navbar.html
{% load static %}
{% load cart_template_tags %}

<nav class="navbar navbar-sticky fixed-top navbar-expand-lg py-2">
  <div class="container">

      <a class="navbar-brand text-dark" href="/">
          <i class="icon icon-layers"></i>
          <strong>Achia</strong>
      </a>

      <div class="d-flex d-lg-none">
          <ul class="navbar-nav flex-row">
              <li class="nav-item">
                  <a href="{% url 'core:order-summary' %}" class="d-flex nav-link">
                      <div class="px-2 py-1">Cart <sup>{{ cart_item_count }}</sup></div>
                  </a>
              </li>
          </ul>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNavbar" aria-controls="furnitureNavbar" aria-expanded="false" aria-label="Toggle navigation">
              <span class="icon icon-menu"></span>
          </button>
      </div>

      <!-- Navbar collapse -->

      <div class="navbar-collapse collapse navbar-collapse-sidebar" id="mainNavbar">

          <div class="d-block d-lg-none">
              <div class="p-3">
                  <div class="d-flex justify-content-between align-items-center">
                      <div>
                          <i class="icon icon-layers"></i>
                          <strong>Achia</strong>
                      </div>
                      <button class="btn p-0" type="button" data-toggle="collapse" data-target="#mainNavbar" aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
                          <span class="icon icon-cross font-size-lg"></span>
                      </button>
                  </div>
              </div>
          </div>

          <ul class="navbar-nav ml-auto align-items-lg-center">
              <li class="nav-item active">
                  <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item dropdown px-lg-3">
                  <a class="nav-link dropdown-toggle" href="#" id="dropdown-shop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Shop
                  </a>
                  <div class="dropdown-menu" aria-labelledby="dropdown-shop">
                      <a class="dropdown-item" href="#">Shop</a>
                      <a class="dropdown-item" href="#">Product</a>
                      <a class="dropdown-item" href="#">Checkout</a>
                  </div>
              </li>
              <li class="nav-item px-lg-3">
                  <a class="nav-link" href="/collection">Collection</a>
              </li>
             
              <li class="nav-item d-none d-lg-inline ml-lg-5">
                  <a href="{% url 'account_logout' %}" class="nav-link">
                      <span class="icon icon-user"></span>
                  </a>
              </li>
              <li class="nav-item d-none d-lg-inline">
                  <a href="{% url 'core:order-summary' %}" class="nav-link d-flex">
                      <div class="px-2 py-1">
                          <span class="icon icon-cart"></span>
                          <sup>{{ cart_item_count }}</sup>
                      </div>
                  </a>
              </li>
             
          </ul>
      </div>

  </div>
</nav>

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">Rs{{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}

    <li class="list-group-item d-flex justify-content-between">
        <span>Total (RS)</span>
        <strong>Rs{{ order.get_total }}</strong>
    </li>
    </ul>

</div>

templates/order_summary.html
{% extends "base.html" %}

{% block extra_head %}
<script src="https://js.stripe.com/v3/"></script>
{% endblock %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                Rs {{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving Rs {{ order_item.get_amount_saved }}</span>
            {% else %}
                Rs {{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
      
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>Rs {{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' id="checkout-button" >Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
    {% csrf_token %}
  </main>

{% endblock content %}


{% block extra_scripts %}


<script type="text/javascript">

    // Create an instance of the Stripe object with your publishable API key
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    var stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");

    var checkoutButton = document.getElementById("checkout-button");

    checkoutButton.addEventListener("click", function () {

      fetch("{% url 'core:create-checkout-session' %}", {

        method: "POST",
        headers: {
            'X-CSRFToken': csrftoken
        }
      })
        .then(function (response) {
          return response.json();
        })
        .then(function (session) {
          return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(function (result) {

          // If redirectToCheckout fails due to a browser or network

          // error, you should display the localized error message to your

          // customer using error.message.
          if (result.error) {
            alert(result.error.message);

          }

        })

        .catch(function (error) {

          console.error("Error:", error);

        });

    });
    document.querySelector("button").disabled = true;

  </script>

{% endblock extra_scripts %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

templates/scripts.html
{% load static %}

<script src="{ static 'js/vendor/jquery.min.js' %}"></script>
<script src="{ static 'js/vendor/bootstrap.bundle.js' %}"></script>
<script src="{ static 'js/vendor/in-view.min.js' %}"></script>
<script src="{ static 'js/vendor/jquery.lavalamp.js' %}"></script>
<script src="{ static 'js/vendor/owl.carousel.js' %}"></script>
<script src="{ static 'js/vendor/rellax.js' %}"></script>
<script src="{ static 'js/vendor/wow.js' %}"></script>
<script src="{ static 'js/vendor/tabzy.js' %}"></script>
<script src="{ static 'js/vendor/isotope.pkgd.js' %}"></script>

<!-- Template Scripts -->

<script src="{ static 'js/main.js' %}"></script>
<script src="{ static 'js/custom.js' %}"></script>